### ISSUE TITLE
[Request] Add Eyezor as a miniboss

### ISSUE THREAD

**Issue by vizthex123** [Flashkirby/Yet-Another-Boss-Health-Bar#2]
It's got 1k HP, and I think that counts.

Though, it's more of a miniboss in expert mode; so maybe expert-only and/or a config option?

Maybe after Mothron can start spawning, it doesn't have a bar anymore?

**Comment by Flashkirby** [comment]
Hmm I would still consider mobs like that to be difficult but not all-encompasing NPCs. The biggest example of something being a miniboss is that it takes up a large number of spawn slots, so that usually only two or three can exist at most and they are necessary to be made aware of, think the minibosses in the halloween and winter themed moon waves.

But yeah I can see the appeal, I may consider adding a config for this. However this mod is on hiatus as the upcoming 1.4 resolves the problem that was the reason for this mod's inception (health bars). If there is still suffecient need for this mod then I will look at updating it further with more configurations - it is already open source.
